"use client";

import React from "react";
import { ShieldAlert } from "lucide-react";

export function Disclaimer({ className = "" }: { className?: string }) {
  return (
    <aside
      role="note"
      aria-label="Fictional simulation disclaimer"
      className={`max-w-4xl mx-auto w-full px-5 py-3.5 rounded-2xl bg-zinc-950/70 border border-white/[0.08] backdrop-blur-md text-center shadow-lg ${className}`}
    >
      <div className="flex items-center justify-center gap-2 mb-1.5 text-zinc-400 font-mono font-medium tracking-wider uppercase text-[11px]">
        <ShieldAlert className="w-3.5 h-3.5 text-amber-400" />
        <span>Fictional Experience Notice</span>
      </div>
      <p className="text-[11px] sm:text-xs font-mono text-zinc-400 leading-relaxed">
        ALMOST is a fictional experience. Nothing you do here purchases an item, books a trip, transfers money, or creates a real reservation. Tickets, boarding passes, confirmations, balances, and rewards generated by ALMOST have no cash value and cannot be used, claimed, or redeemed for travel, admission, goods, services, or money. No payment is processed.
      </p>
    </aside>
  );
}
